# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tool1_table_cpp <- function(demand, renewable_availability_factor, Renewable_capacity = 200, Curtailment_threshold = 10, storage_energy_level_startvalue = 1140.65589, Efficiency_loading = 0.81, Efficiency_discharging = 0.926) {
    .Call('_REvola_tool1_table_cpp', PACKAGE = 'REvola', demand, renewable_availability_factor, Renewable_capacity, Curtailment_threshold, storage_energy_level_startvalue, Efficiency_loading, Efficiency_discharging)
}

tool2_table_cpp <- function(demand, renewable_availability_factor, Renewable_capacity = 200, Curtailment_threshold = 10, storage_energy_level_startvalue = 0, Efficiency_loading = 0.81, Efficiency_discharging = 0.926, Storage_energy = 1000) {
    .Call('_REvola_tool2_table_cpp', PACKAGE = 'REvola', demand, renewable_availability_factor, Renewable_capacity, Curtailment_threshold, storage_energy_level_startvalue, Efficiency_loading, Efficiency_discharging, Storage_energy)
}

